### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by dh3wr** [websockets/wscat#37]
````
pi@RasPagerC9000PCBTest:~ $ wscat -c ws://echo.websocket.org

/usr/local/lib/node_modules/wscat/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/wscat/bin/wscat:17:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
pi@RasPagerC9000PCBTest:~ $
````
OS: Jessie lite

**Comment by lpinca** [comment]
You need Node.js 4 or greater for `wscat@2`.

**Comment by dh3wr** [comment]
ok thank you.
